apiVersion: apps/v1
kind: Deployment
metadata:
 name: httpd-frontend
spec:
 replicas: 3
 selector:
  matchLabels:
   key: frontend
 template:
  metadata:
   name: frontend-pod
   labels:
    key: frontend
  spec:
   containers:
    - name: frontend-containers
      image: httpd:2.4-alpine